package principal.paint.Frames;

/**
 * miercoles 13, octubre 2021
 * @author juanm
 */
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener; 
import java.util.Objects;

public class JPanel_PaitingBoard extends javax.swing.JPanel implements MouseMotionListener{

    public JPanel_PaitingBoard() {
        x = 0; y = 0;
        initComponents();
        setBounds(0, 0, 875, 575); // x e y son 0, porque este panel esta sobre otro panel
    }
    
    // Metodos a implementar de MouseMotionListener
    @Override
    public void mouseMoved(MouseEvent e){
        //No necesito que haga nada
    }
    
    @Override
    public void mouseDragged(MouseEvent e){
        x = e.getX(); y = e.getY();
        repaint(); //Necesito que se repinte para poder hacer nuevos dibujos
    }
    
    @Override
    public void paint(Graphics g){
        g.fillOval(x, y, 3, 3);
    }
    
    @Override
    public void setBackground(Color c){
        super.setBackground(c);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private Integer x,y;
}   
